dh_doctrine_audit:
    ignored_columns:
        - createdAt
        - updatedAt

    entities:
        Rabble\UserBundle\Entity\User:
            ignored_columns:
                - password
                - image.name
                - image.originalName
                - image.size
                - image.mimeType
                - image.dimensions
