framework:
    cache:
        pools:
            doctrine.query_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.filesystem

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.metadata_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            RabbleUserBundle: xml
            VichUploaderBundle: annotation