ongr_elasticsearch:
  source_directories: [/src/Document]
  analysis:
    analyzer:
      case_insensitive:
        type: custom
        tokenizer: keyword
        filter:
          - lowercase
  indexes:
    Rabble\ContentBundle\Persistence\Document\ContentDocument:
      hosts: ['%env(resolve:ELASTICSEARCH_URL)%']
    Rabble\SnippetBundle\Document\Snippet:
      hosts: ['%env(resolve:ELASTICSEARCH_URL)%']