<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    DH\AuditorBundle\DHAuditorBundle::class => ['all' => true],
    Doctrine\Bundle\PHPCRBundle\DoctrinePHPCRBundle::class => ['all' => true],
    ONGR\ElasticsearchBundle\ONGRElasticsearchBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    Rabble\AdminBundle\RabbleAdminBundle::class => ['all' => true],
    Rabble\DatatableBundle\RabbleDatatableBundle::class => ['all' => true],
    Rabble\UserBundle\RabbleUserBundle::class => ['all' => true],
    Rabble\FieldTypeBundle\RabbleFieldTypeBundle::class => ['all' => true],
    Rabble\SnippetBundle\RabbleSnippetBundle::class => ['all' => true],
    Rabble\MenuBundle\RabbleMenuBundle::class => ['all' => true],
    Rabble\SeoBundle\RabbleSeoBundle::class => ['all' => true],
    Rabble\WebsiteBundle\RabbleWebsiteBundle::class => ['all' => true],
    Rabble\PreviewBundle\RabblePreviewBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Eschmar\TimeAgoBundle\EschmarTimeAgoBundle::class => ['all' => true],
    Rabble\ContentBundle\RabbleContentBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
];
